/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static DB.Db.iud;
import static DB.Db.search;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author abhi
 */
public class checkOut extends javax.swing.JFrame {

    /**
     * Creates new form checkOut
     */
    int uId;
    JTable t;
    String Uname;
    Cashier c;

    public checkOut(double tot, int uId, JTable t, String Uname, Cashier c) {
        this.c = c;
        this.Uname = Uname;
        this.t = t;
        this.uId = uId;
        initComponents();
        jLabel14.setText(String.valueOf(tot));
        
        ImageIcon ii = new ImageIcon(new ImageIcon("src/resourses/images/icon/icon.jpg").getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT));
        
        this.setIconImage(ii.getImage());
        
    }

    public checkOut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(250, 251, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(2, 152, 219));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ENTER CASH AMOUNT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("press (Esc) to cancle");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText(" ");
        jLabel12.setOpaque(true);

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField8.setBorder(null);
        jTextField8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("press (Enter) to Acept");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText(" ");
        jLabel14.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel10)
                                    .addGap(27, 27, 27))
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased

        if (!jTextField8.getText().equals("")) {
            if (Double.parseDouble(jTextField8.getText()) >= Double.parseDouble(jLabel14.getText())) {
                jLabel12.setText(String.valueOf(Double.parseDouble(jTextField8.getText()) - Double.parseDouble(jLabel14.getText())));
            } else {
                jLabel12.setText("");
            }
        }

        if (evt.getKeyCode() == 10) {
            if (!jTextField8.getText().equals("")) {
                if (Double.parseDouble(jTextField8.getText()) >= Double.parseDouble(jLabel14.getText())) {

                    int r = JOptionPane.showConfirmDialog(this, "Are you sure do you want to print receipt", "Conform", JOptionPane.INFORMATION_MESSAGE);

                    if (r == 0) {
//                        print receipt
                        printR();
                    } else if (r == 1) {
                        cancel();
                    }

                } else {

                    JOptionPane.showMessageDialog(this, "Insufficient cash. Unable to proceed", "Warning", JOptionPane.WARNING_MESSAGE);

                }
            }

        } else if (evt.getKeyCode() == 27) {
            this.dispose();
        }
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField8KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkOut().setVisible(true);
            }
        });
    }

    synchronized void printR() {

        if (1 == iud("INSERT INTO `cloth_shop`.`invoice` (`total`, `date`, `employee_id`)"
                + " VALUES ('" + jLabel14.getText() + "', NOW(), '" + this.uId + "');")) {

            int rows = this.t.getRowCount();
            ResultSet rs1 = search("SELECT  MAX(id) as invoiceId FROM invoice;");

            try {
                if (rs1.next()) {
                    for (int x = 0; x < rows; x++) {
                        iud("INSERT INTO `cloth_shop`.`invoice_product` (`qty`, `invoice_id`, `product_id`)"
                                + " VALUES ('" + this.t.getValueAt(x, 4) + "', '" + rs1.getString("invoiceId") + "', '" + this.t.getValueAt(x, 0) + "');");

                        iud("UPDATE `cloth_shop`.`stock` SET qty = qty-" + Integer.parseInt(this.t.getValueAt(x, 4).toString()) + " WHERE  `product_id`='" + this.t.getValueAt(x, 0) + "';");

                      
                        
                    }

                    iud("INSERT INTO `cloth_shop`.`transaction` (`amount`, `date`, `employee_id`, `invoice_id`, `status`)"
                            + " VALUES ('" + Double.parseDouble(jTextField8.getText()) + "', NOW(), '" + this.uId + "', '" + rs1.getString("invoiceId") + "', 'Paid');");
                    
                      try {
                        String path = "src//reports//nInvoice.jasper";
                        
                        HashMap<String, Object> map = new HashMap<>();
                        map.put("Parameter1",rs1.getString("invoiceId"));
                        map.put("Parameter2", this.Uname);
                        map.put("Parameter3", jLabel14.getText());
                        map.put("Parameter4", jTextField8.getText());
                        map.put("Parameter5", "0.00");
                        
                        TableModel model = this.t.getModel();
                        
                        JRTableModelDataSource tabelDataSource = new JRTableModelDataSource(model);
                        
                            JasperPrint print = JasperFillManager.fillReport(path, map, tabelDataSource);
                            
                            JasperViewer.viewReport(print,false);
                            
                        } catch (JRException ex) {
                            Logger.getLogger(checkOut.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    
                    
                    clear();
                }
            } catch (SQLException ex) {
                Logger.getLogger(checkOut.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }

    synchronized void cancel() {

        if (1 == iud("INSERT INTO `cloth_shop`.`invoice` (`total`, `date`, `employee_id`)"
                + " VALUES ('" + jLabel14.getText() + "', NOW(), '" + this.uId + "');")) {

            int rows = this.t.getRowCount();
            ResultSet rs1 = search("SELECT  MAX(id) as invoiceId FROM invoice;");

            try {
                if (rs1.next()) {
                    for (int x = 0; x < rows; x++) {
                        iud("INSERT INTO `cloth_shop`.`invoice_product` (`qty`, `invoice_id`, `product_id`)"
                                + " VALUES ('" + this.t.getValueAt(x, 4) + "', '" + rs1.getString("invoiceId") + "', '" + this.t.getValueAt(x, 0) + "');");

                        iud("UPDATE `cloth_shop`.`stock` SET qty = qty-" + Integer.parseInt(this.t.getValueAt(x, 4).toString()) + " WHERE  `product_id`='" + this.t.getValueAt(x, 0) + "';");

                    }

                    iud("INSERT INTO `cloth_shop`.`transaction` (`amount`, `date`, `employee_id`, `invoice_id`, `status`)"
                            + " VALUES ('" + Double.parseDouble(jTextField8.getText()) + "', NOW(), '" + this.uId + "', '" + rs1.getString("invoiceId") + "', 'Cancelled');");
                    clear();
                }
            } catch (SQLException ex) {
                Logger.getLogger(checkOut.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }

    void print() {

    }

    synchronized void clear() {

        TableModel model = this.t.getModel();
        DefaultTableModel dtm = (DefaultTableModel) model;
        dtm.setRowCount(0);
        this.c.jLabel3.setText("0.00");
        this.c.jLabel22.setText("0.00");
        this.c.jLabel25.setText("0.00");
        this.c.jLabel29.setText("0.00");
        this.dispose();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
